export const DummyData = {
  mainSlider: [
    {
      id : 1,
      link: "/",
      imageUrl: "slide1.png",
    },
    {
      id : 2,
      link: "/",
      imageUrl: "slide2.png",
    },
    {
      id : 3,
      link: "/",
      imageUrl: "slide3.png",
    },
    {
      id : 4,
      link: "/",
      imageUrl: "slide4.png",
    },
    {
      id : 5,
      link: "/",
      imageUrl: "slide5.png",
    },
    {
      id : 6,
      link: "/",
      imageUrl: "slide1.png",
    },
  ],
  mainGoods: [
    {
      id : 1,
      link: "/product",
      goodsName: "크라프트 선물 박스 (소)",
      imageUrl: "goods1.png",
      price: 1200,
    },
    {
      id : 2,
      link: "/product",
      goodsName: "블랙 리본 박스",
      imageUrl: "goods2.png",
      price: 2500,
    },
    {
      id : 3,
      link: "/product",
      goodsName: "오픈형 크라프트 박스",
      imageUrl: "goods3.png",
      price: 1800,
    },
    {
      id : 4,
      link: "/product",
      goodsName: "베이지 큐브 박스",
      imageUrl: "goods4.png",
      price: 1500,
    },
    {
      id : 5,
      link: "/product",
      goodsName: "골드 레터링 박스",
      imageUrl: "goods5.png",
      price: 3200,
    },
    {
      id : 6,
      link: "/product",
      goodsName: "화이트 정사각 박스",
      imageUrl: "goods6.png",
      price: 1400,
    },
    {
      id : 7,
      link: "/product",
      goodsName: "크라프트 선물 박스 (중)",
      imageUrl: "goods7.png",
      price: 1600,
    },
    {
      id : 8,
      link: "/product",
      goodsName: "심플 크라프트 박스",
      imageUrl: "goods8.png",
      price: 1100,
    },
    {
      id : 9,
      link: "/product",
      goodsName: "프리미엄 블랙 박스",
      imageUrl: "goods9.png",
      price: 2800,
    },
    {
      id : 10,
      link: "/product",
      goodsName: "디스플레이 박스 세트",
      imageUrl: "goods10.png",
      price: 4500,
    },
  ],
};
